# Generated by Django 5.0.6 on 2024-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='postsl_code',
            new_name='postal_code',
        ),
    ]
